// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.21.1
// source: cmds.proto

package cmds

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ShellCommandRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cmd string `protobuf:"bytes,1,opt,name=cmd,proto3" json:"cmd,omitempty"`
}

func (x *ShellCommandRequest) Reset() {
	*x = ShellCommandRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmds_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShellCommandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShellCommandRequest) ProtoMessage() {}

func (x *ShellCommandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cmds_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShellCommandRequest.ProtoReflect.Descriptor instead.
func (*ShellCommandRequest) Descriptor() ([]byte, []int) {
	return file_cmds_proto_rawDescGZIP(), []int{0}
}

func (x *ShellCommandRequest) GetCmd() string {
	if x != nil {
		return x.Cmd
	}
	return ""
}

type ShellCommandResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Output []byte `protobuf:"bytes,1,opt,name=output,proto3" json:"output,omitempty"`
}

func (x *ShellCommandResponse) Reset() {
	*x = ShellCommandResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmds_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShellCommandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShellCommandResponse) ProtoMessage() {}

func (x *ShellCommandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cmds_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShellCommandResponse.ProtoReflect.Descriptor instead.
func (*ShellCommandResponse) Descriptor() ([]byte, []int) {
	return file_cmds_proto_rawDescGZIP(), []int{1}
}

func (x *ShellCommandResponse) GetOutput() []byte {
	if x != nil {
		return x.Output
	}
	return nil
}

var File_cmds_proto protoreflect.FileDescriptor

var file_cmds_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x63, 0x6d, 0x64, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x27, 0x0a, 0x13,
	0x53, 0x68, 0x65, 0x6c, 0x6c, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x63, 0x6d, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x63, 0x6d, 0x64, 0x22, 0x2e, 0x0a, 0x14, 0x53, 0x68, 0x65, 0x6c, 0x6c, 0x43, 0x6f,
	0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a,
	0x06, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x6f,
	0x75, 0x74, 0x70, 0x75, 0x74, 0x32, 0x4d, 0x0a, 0x05, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x12, 0x44,
	0x0a, 0x0f, 0x52, 0x75, 0x6e, 0x53, 0x68, 0x65, 0x6c, 0x6c, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e,
	0x64, 0x12, 0x15, 0x2e, 0x53, 0x68, 0x65, 0x6c, 0x6c, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x1a, 0x14, 0x2e, 0x53, 0x68, 0x65, 0x6c, 0x6c,
	0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x00,
	0x28, 0x01, 0x30, 0x01, 0x42, 0x08, 0x5a, 0x06, 0x2e, 0x2f, 0x63, 0x6d, 0x64, 0x73, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_cmds_proto_rawDescOnce sync.Once
	file_cmds_proto_rawDescData = file_cmds_proto_rawDesc
)

func file_cmds_proto_rawDescGZIP() []byte {
	file_cmds_proto_rawDescOnce.Do(func() {
		file_cmds_proto_rawDescData = protoimpl.X.CompressGZIP(file_cmds_proto_rawDescData)
	})
	return file_cmds_proto_rawDescData
}

var file_cmds_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_cmds_proto_goTypes = []interface{}{
	(*ShellCommandRequest)(nil),  // 0: ShellCommandRequest
	(*ShellCommandResponse)(nil), // 1: ShellCommandResponse
}
var file_cmds_proto_depIdxs = []int32{
	1, // 0: Agent.RunShellCommand:input_type -> ShellCommandResponse
	0, // 1: Agent.RunShellCommand:output_type -> ShellCommandRequest
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_cmds_proto_init() }
func file_cmds_proto_init() {
	if File_cmds_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_cmds_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShellCommandRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmds_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShellCommandResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cmds_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cmds_proto_goTypes,
		DependencyIndexes: file_cmds_proto_depIdxs,
		MessageInfos:      file_cmds_proto_msgTypes,
	}.Build()
	File_cmds_proto = out.File
	file_cmds_proto_rawDesc = nil
	file_cmds_proto_goTypes = nil
	file_cmds_proto_depIdxs = nil
}
