# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import cmds_pb2 as cmds__pb2


class AgentManagerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RunEchoCommand = channel.unary_unary(
                '/AgentManager/RunEchoCommand',
                request_serializer=cmds__pb2.EchoCommandRequest.SerializeToString,
                response_deserializer=cmds__pb2.EchoCommandResponse.FromString,
                )
        self.RunShellCommand = channel.unary_unary(
                '/AgentManager/RunShellCommand',
                request_serializer=cmds__pb2.ShellCommandRequest.SerializeToString,
                response_deserializer=cmds__pb2.ShellCommandResponse.FromString,
                )
        self.GetAgents = channel.unary_stream(
                '/AgentManager/GetAgents',
                request_serializer=cmds__pb2.Empty.SerializeToString,
                response_deserializer=cmds__pb2.AgentInfo.FromString,
                )


class AgentManagerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RunEchoCommand(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RunShellCommand(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAgents(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AgentManagerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RunEchoCommand': grpc.unary_unary_rpc_method_handler(
                    servicer.RunEchoCommand,
                    request_deserializer=cmds__pb2.EchoCommandRequest.FromString,
                    response_serializer=cmds__pb2.EchoCommandResponse.SerializeToString,
            ),
            'RunShellCommand': grpc.unary_unary_rpc_method_handler(
                    servicer.RunShellCommand,
                    request_deserializer=cmds__pb2.ShellCommandRequest.FromString,
                    response_serializer=cmds__pb2.ShellCommandResponse.SerializeToString,
            ),
            'GetAgents': grpc.unary_stream_rpc_method_handler(
                    servicer.GetAgents,
                    request_deserializer=cmds__pb2.Empty.FromString,
                    response_serializer=cmds__pb2.AgentInfo.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'AgentManager', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class AgentManager(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RunEchoCommand(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/AgentManager/RunEchoCommand',
            cmds__pb2.EchoCommandRequest.SerializeToString,
            cmds__pb2.EchoCommandResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RunShellCommand(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/AgentManager/RunShellCommand',
            cmds__pb2.ShellCommandRequest.SerializeToString,
            cmds__pb2.ShellCommandResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetAgents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/AgentManager/GetAgents',
            cmds__pb2.Empty.SerializeToString,
            cmds__pb2.AgentInfo.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
